version: 2

before:
  hooks:
    - go mod download
builds:
  - binary: a16s
    dir: cmd/a16s
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto
  mode: append

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^ci:'
      - '^test:'
      - '^deps:'
      - '^bump:'
      - '^Merge pull request'
      - '^Merge branch'

universal_binaries:
  - replace: true

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
