version: 2

before:
  hooks:
    - go mod download
builds:
  - binary: a16s
    dir: cmd/a16s
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^ci:'
      - '^test:'
      - '^deps:'
      - '^bump:'
      - '^Merge pull request'
      - '^Merge branch'

universal_binaries:
  - replace: true

brews:
  - name: a16s
    homepage: https://github.com/mohsiur/a16s
    description: a16s is a terminal application to browse and manage AWS resources (ECS, Lambda, SQS, DynamoDB), inspired by k9s.
    repository:
      owner: mohsiur
      name: homebrew-tap

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
